### ISSUE TITLE
#include "mrb/cxx/helpers.hxx" not found.

### ISSUE THREAD

**Issue by lihaochen910** [IceDragon200/mruby-sfml#1]
Did you forget to commit it?

cxx_mrb_cast
cxx_mrb_get_arg
cxx_mrb_data_get_ptr
cxx_mrb_numeric_value
cxx_mrb_data_free
...

**Comment by IceDragon200** [comment]
Sorta, it's in a different repository https://github.com/IceDragon200/mruby-idextmacros/blob/master/include/mrb/cxx/helpers.hxx, I can add the file in question here, I don't see any problems with that.

Give me a few minutes, I need to do a test build
